-- MySQL Script generated by MySQL Workbench
-- Thu Dec  4 14:55:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
 
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `Bericht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bericht` (
  `idbericht` INT NOT NULL,
  `bericht_inhoud` LONGTEXT NOT NULL,
  `verzender` INT NOT NULL,
  PRIMARY KEY (`idbericht`),
  INDEX `fk_Bericht_User1_idx` (`verzender` ASC) VISIBLE,
  CONSTRAINT `fk_Bericht_User1`
    FOREIGN KEY (`verzender`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `Ontvanger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ontvanger` (
  `Bericht_idbericht` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Bericht_idbericht`, `User_idUser`),
  INDEX `fk_User_has_message_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_message_Bericht`
    FOREIGN KEY (`Bericht_idbericht`)
    REFERENCES `Bericht` (`idbericht`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_message_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `Ontvanger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ontvanger` (
  `Bericht_idbericht` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Bericht_idbericht`, `User_idUser`),
  INDEX `fk_User_has_message_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_message_Bericht`
    FOREIGN KEY (`Bericht_idbericht`)
    REFERENCES `Bericht` (`idbericht`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_message_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `Verzender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Verzender` (
  `idVerzender` INT NOT NULL,
  PRIMARY KEY (`idVerzender`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `Ontvanger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ontvanger` (
  `Bericht_idbericht` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Bericht_idbericht`, `User_idUser`),
  INDEX `fk_User_has_message_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_message_Bericht`
    FOREIGN KEY (`Bericht_idbericht`)
    REFERENCES `Bericht` (`idbericht`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_message_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;